-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 05, 2021 at 05:36 PM
-- Server version: 10.4.14-MariaDB
-- PHP Version: 7.4.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `try`
--

-- --------------------------------------------------------

--
-- Table structure for table `applications`
--

/*CREATE TABLE `applications` (
  `App_ID` int(11) NOT NULL,
  `Application_Name` varchar(100) NOT NULL,
  `NumOfUsers` int(11) NOT NULL DEFAULT 0,
  `Price` decimal(10,0) NOT NULL DEFAULT 9999,
  `Sale` decimal(10,0) DEFAULT NULL,
  `AgeRating` int(11) NOT NULL DEFAULT 18,
  `System_Requirements` text DEFAULT NULL,
  `Rating` decimal(10,0) DEFAULT NULL,
  `Application_Picture` text DEFAULT NULL,
  `Application_Link` text DEFAULT NULL,
  `AppDescription` text DEFAULT NULL,
  `AppTrailer` text DEFAULT NULL,
  `Region` varchar(100) DEFAULT NULL,
  `Hide` varchar(1) DEFAULT NULL,
  `Release_Date` date DEFAULT NULL,
  `U_ID` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;*/

--
-- Dumping data for table `applications`
--

INSERT INTO `applications` (`App_ID`, `Application_Name`, `NumOfUsers`, `Price`, `Sale`, `AgeRating`, `System_Requirements`, `Rating`, `Application_Picture`, `Application_Link`, `AppDescription`, `AppTrailer`, `Region`, `Hide`, `Release_Date`, `U_ID`) VALUES
(15, 'PUBG', 1, '0', '0', 3, 'Android', '2', '../IMAGES/PUBG.jpg', 'https://play.google.com/store/apps/details?id=com.tencent.ig', 'The official PLAYERUNKNOWN\'S BATTLEGROUNDS designed exclusively for mobile. Play free anywhere, anytime. PUBG MOBILE delivers the most intense free-to-play multiplayer action on mobile. Drop in, gear up, and compete. Survive epic 100-player classic battles, payload mode and fast-paced 4v4 team deathmatch and zombie modes. Survival is key and the last one standing wins. When duty calls, fire at will!\r\n\r\nFREE ON MOBILE - Powered by the Unreal Engine 4. Play console quality gaming on the go. Delivers jaw-dropping HD graphics and 3D sound. Featuring customizable mobile controls, training modes, and voice chat. Experience the most smooth control and realistic ballistics, weapon behavior on mobile.\r\n\r\nMASSIVE BATTLE MAPS - From Erangel to Miramar, Vikendi to Sanhok, compete on these enormous and detailed battlegrounds varying in size, terrain, day/night cycles and dynamic weather – from urban city spaces to frozen tundra, to dense jungles, master each battleground\'s secrets to create your own strategic approach to win.\r\n\r\nDEPTH AND VARIETY – From the 100-player classic mode, the exhilarating payload mode to the lightning-fast Arcade and 4v4 Team Deathmatch modes, as well as the intense Zombie modes. There is something for everyone! There is something for everyone. Play Solo, Duo, and in 4-player Squads. Fire your weapon to your heart\'s content! Be a lone wolf soldier or play with a Clan and answer the duty calls when help is needed! Offers FPS (First-Person Shooter) and TPS (Third-Person Shooter) play, lots of vehicles for all the different terrains in the game and an arsenal of realistic weapons. Find your perfect ride and pieces to cruise towards the final circle!\r\n', 'https://www.youtube.com/embed/CkwvrGBhdI4', 'Everywhere', '0', '2021-01-04', 1),
(16, 'Facebook', 1, '0', '0', 3, 'Andriod OR IOS OR Desktop', '1', '../IMAGES/Facebook.png', 'https://play.google.com/store/apps/details?id=com.facebook.katana', 'Keeping up with friends is faster and easier than ever. Share updates and photos, engage with friends and Pages, and stay connected to communities important to you.\r\n\r\nFeatures on the Facebook app include:\r\n\r\n* Connect with friends and family and meet new people on your social media network\r\n* Set status updates & use Facebook emoji to help relay what’s going on in your world\r\n* Share photos, videos, and your favorite memories.\r\n* Get notifications when friends like and comment on your posts\r\n* Find local social events, and make plans to meet up with friends\r\n* Play games with any of your Facebook friends\r\n* Backup photos by saving them in albums\r\n* Follow your favorite artists, websites, and companies to get their latest news\r\n* Look up local businesses to see reviews, operation hours, and pictures\r\n* Buy and sell locally on Facebook Marketplace\r\n* Watch live videos on the go\r\n\r\n\r\nThe Facebook app does more than help you stay connected with your friends and interests. It\'s also your personal organizer for storing, saving and sharing photos. It\'s easy to share photos straight from your Android camera, and you have full control over your photos and privacy settings. You can choose when to keep individual photos private or even set up a secret photo album to control who sees it.\r\n\r\nFacebook also helps you keep up with the latest news and current events around the world. Subscribe to your favorite celebrities, brands, news sources, artists, or sports teams to follow their newsfeeds, watch live streaming videos and be caught up on the latest happenings no matter where you are!\r\n\r\nThe most important desktop features of Facebook are also available on the app, such as writing on timelines, liking photos, browsing for people, and editing your profile and groups.', 'https://www.youtube.com/embed/Tksg37VN8mA', 'Everywhere', '0', '2021-01-04', 2),
(17, 'Twitter', 1, '0', '0', 3, 'No thing', '5', '../IMAGES/Twitter.png', 'https://play.google.com/store/apps/details?id=com.twitter.android', 'Retweet, chime in on a thread, go viral, or just scroll through the Twitter timeline to stay on top of what everyone’s talking about. Twitter is your go-to social media app and the new media source for what\'s happening in the world, straight from the accounts of the influential people who affect your world day-to-day.\r\n\r\nExplore what’s trending in the media, or get to know thought-leaders in the topics that matter to you; whether your interests range from #Kpop Twitter to politics, news or sports, you can follow & speak directly to influencers or your friends alike. Every voice can impact the world.\r\n\r\nFollow your interests. ⭐ Tweet, Fleet, Retweet, Reply to Tweets, Share or Like - Twitter is the #1 social media app for latest news & updates.\r\n\r\nTap into what’s going on around you. Search hashtags and trending topics to stay updated on your friends & other Twitter followers. Follow the tweets of your favorite influencers, alongside hundreds of interesting Twitter users, and read their content at a glance.\r\n\r\nShare your opinion. Engage your social network with noteworthy links, photos and videos. DM your friends or reply in a thread. Whether you chat privately or go viral, your voice makes a difference.\r\n\r\nGet noticed. Twitter allows you to find interesting people or build a following of people who are interested in you. Maintaining a social connection has never been easier! Beyond chatting with friends, Twitter allows influencers to build a personal connection with their fans. Speak directly to the people who influence you - you may be surprised by how many answer back', NULL, 'Everywhere', '0', '2021-01-04', 3),
(18, 'Clash of Clans', 0, '0', '0', 3, '', '5', '../IMAGES/Clash of Clans.jpg', 'https://play.google.com/store/apps/details?id=com.supercell.clashofclans', 'Join millions of players worldwide as you build your village, raise a clan, and compete in epic Clan Wars!\r\n\r\nMustachioed Barbarians, fire wielding Wizards, and other unique troops are waiting for you! Enter the world of Clash!\r\n\r\nNew Features:\r\n● Roll through enemy villages with the Log Launcher, a brand-new Siege Machine!\r\n● Introducing Super Wizard and Ice Hound, the latest additions to the Super Troop line-up!\r\n● Update also contains a new, must-see Spell, fresh Town Hall 13 content, neat quality of life changes and much more!\r\n\r\nClassic Features:\r\n● Join a Clan of fellow players or start your own and invite friends.\r\n● Fight in Clan Wars as a team against millions of active players across the globe.\r\n● Test your skills in the competitive Clan War Leagues and prove you’re the best.\r\n● Forge alliances, work together with your Clan in Clan Games to earn valuable Magic items.\r\n● Plan your unique battle strategy with countless combinations of Spells, Troops, and Heroes!\r\n● Compete with the best players from around the world and rise to the top of the Leaderboard in Legend League.\r\n● Collect resources and steal loot from other players to upgrade your own Village and turn it into a stronghold.\r\n● Defend against enemy attacks with a multitude of Towers, Cannons, Bombs, Traps, Mortars, and Walls.\r\n● Unlock epic Heroes like the Barbarian King, Archer Queen, Grand Warden, Royal Champion, and Battle Machine.\r\n● Research upgrades in your Laboratory to make your Troops, Spells, and Siege Machines even more powerful.\r\n● Create your own custom PVP experiences through Friendly Challenges, Friendly Wars, and special live events.\r\n● Watch Clanmates attack and defend in real-time as a spectator or check out the video replays.\r\n● Fight against the Goblin King in a single player campaign mode through the realm.\r\n● Learn new tactics and experiment with your army and Clan Castle troops in Practice Mode.\r\n● Journey to the Builder Base and discover new buildings and characters in a mysterious world.\r\n● Turn your Builder Base into an unbeatable fortress and defeat rival players in Versus Battles.\r\n● Collect exclusive Hero Skins and Sceneries to customize your Village.', NULL, 'Everywhere', '0', '2021-01-04', 4),
(19, 'Subway Surfers', 0, '0', '0', 3, '', '5', '../IMAGES/Subway Surfers.jpg', 'https://play.google.com/store/apps/details?id=com.kiloo.subwaysurf', 'DASH as fast as you can!\r\nDODGE the oncoming trains!\r\n\r\nHelp Jake, Tricky & Fresh escape from the grumpy Inspector and his dog.\r\n\r\n★ Grind trains with your cool crew!\r\n★ Colorful and vivid HD graphics!\r\n★ Hoverboard Surfing!\r\n★ Paint powered jetpack!\r\n★ Lightning fast swipe acrobatics!\r\n★ Challenge and help your friends!\r\n\r\nJoin the most daring chase!\r\n\r\nA Universal App with HD optimized graphics.\r\n\r\nBy Kiloo and Sybo.', NULL, 'Everywhere', '0', '2021-01-04', 5),
(20, 'Temple Run', 1, '10', '0', 3, '', '3', '../IMAGES/Temple Run.webp', 'https://play.google.com/store/apps/details?id=com.imangi.templerun', 'The addictive mega-hit Temple Run is now out for Android! All your friends are playing it - can you beat their high scores?!\r\n\r\nYou\'ve stolen the cursed idol from the temple, and now you have to run for your life to escape the Evil Demon Monkeys nipping at your heels. Test your reflexes as you race down ancient temple walls and along sheer cliffs. Swipe to turn, jump and slide to avoid obstacles, collect coins and buy power ups, unlock new characters, and see how far you can run!\r\n\r\n\"In every treasure hunting adventure movie there’s one scene in which the plucky hero finally gets his hands on the treasure but then has to navigate a maze of booby traps in order to get out alive. Temple Run is this scene and nothing else. And it’s amazing.\" - SlideToPlay.com\r\n', NULL, 'Everywhere', '0', '2021-01-04', 6),
(21, 'Google Drive', 1, '10', '0', 3, '', '1', '../IMAGES/Google Drive.png', 'https://play.google.com/store/apps/details?id=com.google.android.apps.docs', 'Google Drive is a safe place to back up and access all your files from any device. Easily invite others to view, edit, or leave comments on any of your files or folders.\r\n\r\nWith Drive, you can:\r\n\r\n• Safely store and access your files anywhere\r\n• Quickly access recent and important files\r\n• Search for files by name and content\r\n• Share and set permissions for files and folders\r\n• View your content on the go while offline\r\n• Receive notifications about important activity on your files\r\n• Use your device’s camera to scan paper documents', NULL, 'Everywhere', '0', '2021-01-04', 7),
(22, 'Google Classroom', 0, '10', '0', 3, '', '2', '../IMAGES/Google Classroom.jpg', 'https://play.google.com/store/apps/details?id=com.google.android.apps.classroom', 'Classroom is a free service for schools, non-profits, and anyone with a personal Google account. Classroom makes it easy for learners and instructors to connect—inside and outside of schools. Classroom saves time and paper, and makes it easy to create classes, distribute assignments, communicate, and stay organized.\r\n\r\nThere are many benefits to using Classroom:\r\n• Easy to set up – Teachers can add students directly or share a code with their class to join. It takes just minutes to set up.\r\n• Saves time – The simple, paperless assignment workflow allows teachers to create, review and mark assignments quickly, all in one place.\r\n• Improves organization – Students can see all of their assignments on an assignments page, and all class materials (e.g., documents, photos, and videos) are automatically filed into folders in Google Drive.\r\n• Enhances communication – Classroom allows teachers to send announcements and start class discussions instantly. Students can share resources with each other or provide answers to questions on the stream.\r\n• Affordable and secure – Like the rest of G Suite for Education services, Classroom contains no ads, never uses your content or student data for advertising purposes, and is free.', NULL, 'Everywhere', '0', '2021-01-04', 484),
(23, 'Gmail', 0, '0', '0', 3, '', '2', '../IMAGES/Gmail.png', 'https://play.google.com/store/apps/details?id=com.google.android.gm', 'Gmail is an easy to use email app that saves you time and keeps your messages safe. Get your messages instantly via push notifications, read and respond online & offline, and find any message quickly.\r\nWith the Gmail app you get:\r\n• An organized inbox - Social and promotional messages are sorted into categories so you can read messages from friends and family first.\r\n• Less spam - Gmail blocks spam before it hits your inbox to keep your account safe and clutter free.\r\n• 15GB of free storage - You won’t need to delete messages to save space.\r\n• Multiple account support - Use both Gmail and non-Gmail addresses (Outlook.com, Yahoo Mail, or any other IMAP/POP email) right from the app.\r\n', NULL, 'Everywhere', '0', '2021-01-04', 484),
(24, 'Instagram', 0, '0', '0', 15, '', '3', '../IMAGES/Instagram.jpg', 'https://play.google.com/store/apps/details?id=com.instagram.android', 'Bringing you closer to the people and things you love. — Instagram from Facebook\r\n\r\nConnect with friends, share what you’re up to, or see what\'s new from others all over the world. Explore our community where you can feel free to be yourself and share everything from your daily moments to life\'s highlights.\r\n\r\nExpress Yourself and Connect With Friends\r\n\r\n* Add photos and videos to your INSTA story that disappear after 24 hours, and bring them to life with fun creative tools.\r\n* Message your friends in Direct. Start fun conversations about what you see on Feed and Stories.\r\n* Post photos and videos to your feed that you want to show on your profile.\r\n\r\nLearn More About Your Interests\r\n\r\n* Check out IGTV for longer videos from your favorite INSTA creators.\r\n* Get inspired by photos and videos from new INSTA accounts in Explore.\r\n* Discover brands and small businesses, and shop products that are relevant to your personal ', NULL, 'Everywhere', '0', '2021-01-04', 484),
(25, 'Snapchat', 0, '0', '0', 3, 'Android', '3', '../IMAGES/Snapchat.png', 'https://play.google.com/store/apps/details?id=com.snapchat.android', 'Snapchat is a fast and fun way to share the moment with friends and family 👻\r\n\r\nSnapchat opens right to the camera, so you can send a Snap in seconds! Just take a photo or video, add a caption, and send it to your best friends and family. Express yourself with Filters, Lenses, Bitmojis, and all kinds of fun effects.\r\n\r\nSNAP 📸\r\n• Snapchat opens right to the camera. Tap to take a photo, or press and hold for video.\r\n• Add a Lens or Filter to your photo — new ones are added every day! Change the way you look, dance with your 3D Bitmoji, and discover games you can play with your face.\r\n• Create your own Filters to add to photos and videos — or try out Lenses made by our community!\r\n\r\nCHAT 💬\r\n• Stay in touch and Chat with friends with live messaging, or share your day with Group Stories.\r\n• Video Chat with up to 16 friends at once. You can even use Filters and Lenses!\r\n• Express yourself with Friendmojis — exclusive Bitmojis made just for you and a friend.\r\n\r\nSTORIES\r\n• Watch friends\' Stories to see their day unfold.\r\n• Watch Stories from the Snapchat community, based on your interests.\r\n• Explore new perspectives from top creators.\r\n\r\nDISCOVER 🔍\r\n• Watch breaking news and exclusive Original Shows.\r\n• Keep up to date with Stories from top publishers.\r\n• Enjoy a curated feed — made to fit your phone.\r\n\r\nSNAP MAP 🗺\r\n• See where your friends are hanging out, if they’ve shared their location with you.\r\n• Share your location with your best friends, or go off the grid with Ghost Mode.\r\n• Discover live Stories from the community nearby, or across the world!\r\n\r\nMEMORIES 🎞️\r\n• Look back on Snaps you’ve saved with free cloud storage.\r\n• Edit and send old moments to friends, or save them to your Camera Roll.\r\n• Create Stories from your favorite memories to share with friends and family.\r\n', NULL, 'Everywhere', '0', '2021-01-04', 484),
(26, 'SoundCloud ', 1, '0', '0', 3, '', '3', '../IMAGES/SoundCloud .png', 'https://play.google.com/store/apps/details?id=com.soundcloud.android', 'SoundCloud is more than a streaming service, it’s an open global community for anyone to upload any sound for immediate discovery.\r\n\r\nBe the first to hear new tracks, connect directly with fellow fans and your favorite artists in real time, and support the future of music with every play, like, repost and comment.\r\n\r\nGet SoundCloud FREE:\r\n\r\n- Access the most diverse catalog of content\r\n- Discover millions of emerging and established artists, DJs and podcasters\r\n- Listen to music that exists nowhere else\r\n- Get suggested tracks based on your listening habits\r\n- Explore SoundCloud Charts for the best music or podcasts in each genre\r\n- Connect directly with artists and fellow listeners\r\n- Create playlists for any occasion\r\n- Find new music faster with curated playlists', NULL, 'Everywhere', '0', '2021-01-04', 484),
(27, 'SHAREit ', 0, '0', '0', 3, '', '5', '../IMAGES/SHAREit .jpg', 'https://play.google.com/store/apps/details?id=com.lenovo.anyshare.gps', 'SHAREit, excellent sharing app with fast cross-platform transfer speed & free online feeds including movies, videos, music, wallpapers, GIFs. SHAREit also added powerful media player, which helps you manage & enjoy your own videos and music.\r\n\r\n► Fastest in the World\r\n200 times faster than Bluetooth, the highest speed goes up to 20M/s.\r\nTransfer files without losing quality.\r\n\r\n► Transfer All Types of Files\r\nPhotos, videos, music, installed apps and any other files.\r\n\r\n► Infinite Online Videos\r\nHD & Selective, Offline watching, Continuously updated\r\n\r\n► Excellent Video Player\r\nSupport almost all formats, give you Smooth playing experience\r\n\r\n► Discover Trending Music\r\nTens of millions of high quality songs, and thousands of curated playlists. Online & Offline\r\n\r\n► Elegant Music Player\r\nPowerful equalizer provides immersive experiences for you\r\n\r\n►GIFs, Wallpapers & Stickers\r\nPersonalized, Funny, Download & Share', NULL, 'Everywhere', '0', '2021-01-04', 484),
(28, 'Call of Duty', 0, '0', '0', 3, '', '3', '../IMAGES/Call of Duty.jpg', 'https://play.google.com/store/apps/details?id=com.activision.callofduty.shooter', 'Official CALL OF DUTY® designed exclusively for mobile phones. Play iconic multiplayer maps and modes anytime, anywhere. 100 player Battle Royale battleground? Fast 5v5 team deathmatch? Sniper vs sniper battle? Activision’s free-to-play CALL OF DUTY®: MOBILE has it all.\r\n\r\nFREE TO PLAY ON MOBILE\r\n\r\nConsole quality HD gaming on your phone with customizable controls, voice and text chat, and thrilling 3D graphics and sound. Experience the thrill of the world’s most beloved shooter game, now on your phone for easy on-the-go fun.\r\n\r\nBELOVED GAME MODES AND MAPS\r\n\r\nPlay iconic multiplayer maps from Call of Duty®: Black Ops and Call of Duty®: Modern Warfare®, available for the first time for free. Or squad up with friends in a brand new 100-person battle royale survival map. Join the fun with millions of players from all around world!\r\n\r\nCUSTOMIZE YOUR UNIQUE LOADOUT\r\n\r\nAs you play CALL OF DUTY®: MOBILE you will unlock and earn dozens of famous characters, weapons, outfits, scorestreaks and pieces of gear that can be used to customize your loadouts. Bring these loadouts into battle in Battle Royale and thrilling PvP multiplayers modes like Team Deathmatch, Frontline, Free For All, Search and Destroy, Domination, Hardpoint and many more.\r\n\r\nCOMPETITIVE AND SOCIAL PLAY\r\n\r\nUse skill and strategy to battle to the top in competitive Ranked Mode or to win the most Clan prizes as you play with friends. Compete and fight against millions of friends and foes in this thrilling free to play multiplayer shooter.\r\n\r\nCHOICE AND COMPLEXITY\r\n\r\nWhether in gameplay, events, controls, or loadouts, CALL OF DUTY®: MOBILE offers complexity and depth in an ever-changing experience.\r\n', NULL, 'Everywhere', '0', '2021-01-04', 484),
(29, 'Microsoft Word', 0, '0', '0', 3, '', '4', '../IMAGES/Microsoft Word.jpg', 'https://play.google.com/store/apps/details?id=com.microsoft.office.word', 'Read and edit documents attached to emails, collaborate with your team and bring your office wherever you go with Microsoft Word. The Word app from Microsoft lets you create, read, edit, and share your files quickly and easily.\r\n\r\nWord introduces a mobile PDF reader for your phone. Edit documents and read PDFs or e-books while traveling, before bedtime, or wherever you want.\r\n\r\nCreate documents, blogs, write-ups, or resumes on the go. Write letters, resumes, documents, or notes your way with robust tools that enable you to write with the best format options.\r\n\r\nThe writing app and word processor is as handy as you want it to be, whether you’re a blogger, writer, journalist, columnist, student, or a project manager working on documentation. Your office moves with you when you use Microsoft Word.\r\n\r\nWrite a letter, create templates, read Word documents, edit docs and collaborate with your team wherever you are with Microsoft Word.', NULL, 'Everywhere', '0', '2021-01-04', 484),
(30, 'WhatsApp Messenger', 0, '0', '0', 3, '                                                                        ', '5', '../IMAGES/WhatsApp Messenger.jpg', 'https://play.google.com/store/apps/details?id=com.whatsapp', '  WhatsApp Messenger is a FREE messaging app available for Android and other smartphones. WhatsApp uses your phone\'s Internet connection (4G/3G/2G/EDGE or Wi-Fi, as available) to let you message and call friends and family. Switch from SMS to WhatsApp to send and receive messages, calls, photos, videos, documents, and Voice Messages.\r\n\r\nWHY USE WHATSAPP:\r\n\r\n• NO FEES: WhatsApp uses your phone\'s Internet connection (4G/3G/2G/EDGE or Wi-Fi, as available) to let you message and call friends and family, so you don\'t have to pay for every message or call.* There are no subscription fees to use WhatsApp.\r\n\r\n• MULTIMEDIA: Send and receive photos, videos, documents, and Voice Messages.\r\n\r\n• FREE CALLS: Call your friends and family for free with WhatsApp Calling, even if they\'re in another country.* WhatsApp calls use your phone\'s Internet connection rather than your cellular plan\'s voice minutes. (Note: Data charges may apply. Contact your provider for details. Also, you can\'t access 911 and other emergency service numbers through WhatsApp).\r\n\r\n• GROUP CHAT: Enjoy group chats with your contacts so you can easily stay in touch with your friends or family.\r\n\r\n• WHATSAPP WEB: You can also send and receive WhatsApp messages right from your computer\'s browser.\r\n\r\n• NO INTERNATIONAL CHARGES: There\'s no extra charge to send WhatsApp messages internationally. Chat with your friends around the world and avoid international SMS charges.*\r\n\r\n• SAY NO TO USERNAMES AND PINS: Why bother having to remember yet another username or PIN? WhatsApp works with your phone number, just like SMS, and integrates seamlessly with your phone\'s existing address book.\r\n\r\n• ALWAYS LOGGED IN: With WhatsApp, you\'re always logged in so you don\'t miss messages. No more confusion about whether you\'re logged in or logged out.\r\n\r\n• QUICKLY CONNECT WITH YOUR CONTACTS: Your address book is used to quickly and easily connect you with your contacts who have WhatsApp so there\'s no need to add hard-to-remember usernames.\r\n\r\n• OFFLINE MESSAGES: Even if you miss your notifications or turn off your phone, WhatsApp will save your recent messages until the next time you use the app.\r\n\r\n• AND MUCH MORE: Share your location, exchange contacts, set custom wallpapers and notification sounds, broadcast messages to multiple contacts at once, and more!\r\n\r\n*Data charges may apply. Contact your provider for details.', NULL, 'Everywhere', '0', '2021-01-04', 484),
(31, 'LinkedIn', 0, '0', '0', 3, '', '1', '../IMAGES/LinkedIn.png', 'https://play.google.com/store/apps/details?id=com.linkedin.android', 'LinkedIn helps you find the right connections and the right network to help you find a job. Take the first step with LinkedIn to find the perfect career to start the year.\r\n\r\nJob search is easy with LinkedIn. Easily find a career and stay up to date on the most relevant openings with the LinkedIn app, the most trusted network. Go through the most up-to-date job listings and business news, with millions of connections in every industry, right at your fingertips. Filter through millions of openings and customized recommendations to find your perfect career. Safely apply for your perfect position with your resume or professional profile in a few taps, straight through the app.\r\n\r\nGrow your network with business contacts, stay up to date with companies, and follow thought leaders. Taking that first step by adding business connections, sending InMail messages or joining a group will change it all. LinkedIn can help you start the conversations you need to find a job.\r\n\r\nJob seeker looking for new employment? Business networking? Business news and industry buzz? Do that and more with the free LinkedIn app.\r\n\r\nFind a job hiring near you and use LinkedIn to ask your business contacts for referrals. Check online jobs, share posts and converse with fellow professionals to boost your odds of getting hired.\r\n\r\nNo matter where you\'re at or what you\'re looking for, LinkedIn makes job searching easy. Grow and connect with friends, colleagues, companies, industry experts and the rest of the LinkedIn community.\r\n\r\n5 reasons why you’ll love the LinkedIn app:', NULL, 'Everywhere', '0', '2021-01-04', 484),
(32, 'Messenger', 1, '0', '0', 3, '', '5', '../IMAGES/Messenger.webp', 'https://play.google.com/store/apps/details?id=com.facebook.orca', 'Be together whenever, with our free* all-in-one communication app, complete with unlimited text, voice, video calling and group video chat features. Easily sync your messages and contacts to your Android phone and connect with anyone, anywhere.\r\n\r\nCROSS-APP MESSAGING AND CALLING\r\nConnect with your Instagram friends right from Messenger. Simply search for them by name or username to message or call.\r\n\r\nVANISH MODE\r\nSend messages that only last for a moment. Opt in to use vanish mode where seen messages disappear after you exit the chat.\r\n\r\nPRIVACY SETTINGS\r\nNew privacy settings let you choose who can reach you, and where your messages are delivered.\r\n\r\nCUSTOM REACTIONS\r\nLost for words? You can customize your reactions, with lots more emojis to choose from, including 🎉 and 🔥.', NULL, 'Everywhere', '0', '2021-01-04', 484),
(33, 'TikTok', 0, '0', '0', 3, '', '2', '../IMAGES/TikTok.png', 'https://play.google.com/store/apps/details?id=com.zhiliaoapp.musically', 'TikTok is THE destination for mobile videos. On TikTok, short-form videos are exciting, spontaneous, and genuine. Whether you’re a sports fanatic, a pet enthusiast, or just looking for a laugh, there’s something for everyone on TikTok. All you have to do is watch, engage with what you like, skip what you don’t, and you’ll find an endless stream of short videos that feel personalized just for you. From your morning coffee to your afternoon errands, TikTok has the videos that are guaranteed to make your day.\r\n\r\nWe make it easy for you to discover and create your own original videos by providing easy-to-use tools to view and capture your daily moments. Take your videos to the next level with special effects, filters, music, and more.', NULL, 'Everywhere', '0', '2021-01-04', 484),
(34, 'Pinterest', 0, '0', '0', 3, '', '5', '../IMAGES/Pinterest.png', 'https://play.google.com/store/apps/details?id=com.pinterest', 'Looking for creative ideas? Whether you’re planning your next big travel adventure, searching for home design concepts, looking for fashion & fitness tips or checking out new recipes, explore lifestyle inspiration on Pinterest. Good ideas start here!\r\n\r\nDiscover billions of possibilities for every part of your life, from new recipes to creative home design ideas. Create extra home storage space, find your new favorite recipe, or get tattoo inspiration on Pinterest.\r\n\r\nSave ideas on Pinterest:\r\n★ Find lifestyle inspiration & explore articles on trending and recommended topics\r\n\r\n★ Collaborate with friends for your next group trip, party or DIY project\r\n\r\n★ See ideas & images out in the world that you like and snap a photo with Pinterest Lens to find out how to buy/make/do them!\r\n\r\nDiscover wedding tips, beauty inspiration and design concepts for your big day. Explore thousands of recommended or trending images, get travel inspiration or read new recipes and creative food ideas for your next dinner party. With fitness tips, interesting DIY projects to try out and tons of great fashion, style & beauty tips, Pinterest keeps all of your lifestyle inspiration in one place.\r\n\r\nYou never know what sparks a great design idea or when inspiration for your next DIY project might strike.\r\n\r\nGet inspired from anywhere on the internet. Save your ideas, organize them by topic and share with others – all from your pocket!\r\n\r\nGet ideas for the topics you care about most:\r\n- Home design, architecture & DIY\r\n- Creative wedding tips\r\n- Travel, fitness & beauty\r\n- Fashion and style inspiration\r\n- Food, new recipes & cooking\r\n\r\nTo start saving and sharing Pins, download now.', NULL, 'Everywhere', '0', '2021-01-04', 484);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `applications`
--
/*ALTER TABLE `applications`
  ADD PRIMARY KEY (`App_ID`),
  ADD KEY `U_ID` (`U_ID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `applications`
--
ALTER TABLE `applications`
  MODIFY `App_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=35;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `applications`
--
ALTER TABLE `applications`
  ADD CONSTRAINT `applications_ibfk_1` FOREIGN KEY (`U_ID`) REFERENCES `users` (`U_ID`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;*/

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
